### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by CJL92** [volcengine/volcengine-specs#19]
RangersAppLog/RangersAppLog/Core/libRangersAppLog_Core_ios.a  这个里面的方法名currentSession，你们不能换掉吗？每次Xcode14打包都在警告使用私有API

**Comment by 18633142594** [comment]
运行在iOS16.1的手机上，模拟器上，编译会失败，跑不起来。报错如下：
  "_sqlite3_wal_checkpoint", referenced from:
      -[OKKVStorage _dbCheckpoint] in libOneKit_Cache_awesome_ios.a(OKKVStorage.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
